- name: deploy portfolio app
  hosts: server1
  become: true

  tasks:
  - name: update APT pakcages
    apt:
      update_cache: yes

  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Copy HTML file to default location
    copy: 
      src: index.html
      dest: /var/www/html/index.html

  - name: Start Nginx
    service:
      name: nginx
      state: started
      enabled: yes
    